# cargo

# [[file:~/Workspace/Programming/guts/guts.note::*cargo][cargo:1]]
[package]
name = "guts"
version = "0.0.5"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
# core utils
serde = {version="1", features = ["derive"]}
failure = "0.1"
itertools = "0.8"
# logging
log = "^0.4"
pretty_env_logger = "0.4"
# configuration
toml = "0.5"
lazy_static = "1.3"
# command line
structopt = "0.3"
exitfailure = "0.5"
# parallel
rayon = "1"

[dev-dependencies]
# cargo:1 ends here
